name: project_agrinova
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.5.0
  cloud_firestore: 5.4.2
  firebase_auth: 5.3.0
  firebase_storage: 12.3.1
  image_picker: 1.1.2
  image_cropper: 8.0.2
  permission_handler: ^10.2.0  # or the latest version
  firebase_app_check: ^0.3.1+2
  shared_preferences: 2.3.2
  line_awesome_flutter: 3.0.1
  cupertino_icons: ^1.0.6
  flutter_platform_widgets: 7.0.1
  flutter_spinkit: ^5.2.1
  badges: ^3.1.2
  url_launcher: 6.3.1
  lottie: 3.2.0
  photo_manager: 3.6.4
  file_picker: 8.3.3
  intl: ^0.19.0
  easy_localization: ^3.0.0
  provider: 6.1.2
  uuid: 4.5.1
  emoji_regex: 0.0.5
  flutter_chat_ui: 1.6.15
  path_provider: ^2.0.0
  dio: ^5.0.0
  upi_india: ^3.0.1
  google_generative_ai: ^0.4.6
  flutter_tts: 3.6.3
  tflite_flutter: ^0.11.0
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
#  geolocator: ^14.0.0
#  geocoding: ^3.0.0
#  downloads_path_provider: 0.0.1

#  record: 5.2.1
#  just_audio: ^0.9.36
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.3
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Crop_Management/
    - assets/
    - lib/src/Language/en.json
    - lib/src/Language/ta.json
    - assets/images/government_schemes/central_government_schemes/
    - assets/images/government_schemes/state_government_schemes/
    - assets/images/Agri_Products/
    - assets/images/Tractor/
    - assets/images/Soil_sensor/
    - assets/images/Seeders_and_Planters/
    - assets/images/Irrigation_Machines/
    - assets/images/Harvesting_Tool/
    - assets/images/Green_house/
    - assets/images/Fencing/
    - assets/images/Combine_harvesters/
    - assets/images/Agriculture_tool/
    - assets/images/government_schemes/central_government_schemes/
    - assets/images/government_schemes/state_government_schemes/
    - assets/images/government_schemes/state_government_schemes/ktn2.jpg
    - assets/images/fruits/
    - assets/images/medicine plants/
    - assets/images/oilseeds/
    - assets/images/grains and pulses/
    - assets/images/spices/
    - assets/images/vegetables/
    - assets/images/fruits/
    - assets/images/types_of_crops/
    - assets/images/topic_toc/
    - assets/images/vegcb/
    - assets/images/livestocks/
    - assets/images/lvci/


  fonts:
    - family: Alatsi
      fonts:
        - asset: assets/fonts/Alatsi-Regular.ttf

